@startuml Диаграмма классов
  !theme plain
  skinparam BackgroundColor #d2e3fc
  skinparam ClassBorderColor #4940ad
  skinparam ClassBackgroundColor #efedff
  skinparam Handwritten false

  class Message {
    +string text
    +bool isSecure
    +void logMessage()
    +ByteVector convertToBytes()
    +BigInt convertToBigInt()
  }

  abstract Encryption

  class AsymmetricEncryption {
    -KeyPair keys;
    +Message encode(Message m)
    +Message encode(Message m, PublicKey key)
    +Message decode(Message m)
    +Message decode(Message m, PrivateKey key)
  }
  class PublicKey {
    +BigInt e
    +BigInt n
  }
  class PrivateKey {
    +BigInt d
    +BigInt n
  }
  class KeyPair {
    -PublicKey publicKey
    -PrivateKey privateKey
    +PublicKey getPublicKey()
    +PrivateKey getPrivateKey()
  }

  class KeysGenerator {
    #KeyPair keys
    -BigInt getPublicExponent(BigInt φ)
    -BigInt multiplicativeInverseElement(BigInt e, BigInt φ)
    +KeyPair getKeys()
  }

  class Caesar {
    -int shift;
    -CharVector alphabet
    -AlphabetTable alphabetTable
    -int n
    +Message encode(Message m)
    +Message encode(Message m, int shift)
    +Message decode(Message m)
    +Message decode(Message m, int shift)
  }

  class ShannonFano {
    -CharVector alplabet
    -int blockSize
    -SymbolProbabilitiesTable symbolPr
    -ProbabilitiesTable probabilitiesTable
    -Codes codes
    -Codes codesInverse
    -double entropy
    -double avgLen 
    -IntVector uppercasePositions
    -IntVector punctuationPositions
    -CharVector punctuation
    -void createCodes(int start, int end)
    -int getSplitIndex(int start, int end)
    -void sortByProbability(ProbabilitiesTable* t)
    +string savePunctuation(string plainMsg)
    +string withPunctuation(string plainMsg)
    +Message encode(Message m)
    +Message decode(Message m)
  }

  abstract Encoder {
    Message encode(Message m)
  }

  abstract Decoder {
    Message decode(Message m)
  }

  class Encryptor {
    -Encryption* encryption
    +void setStrategy(Encryption* encryption)
    +Message encode(Message m)
    +Message decode(Message m)
  }

  class BigInt {
    -CharVector accumulator
    -bool isNegative
    +void logNumber()
    +size_t length()
    +string getAccumator()
    +string getAccumatorWithSign()
    +bool getIsNegative()
    +BigInt& operator = (const BigInt& other)
    +bool operator == (BigInt other)
    +bool operator < (BigInt other)
    +bool operator > (BigInt other)
    +bool operator <= (BigInt other)
    +bool operator >= (BigInt other)
    +BigInt operator + (BigInt b)
    +BigInt& operator ++ (int)
    +BigInt& operator += (BigInt& other)
    +BigInt operator - (BigInt b)
    +BigInt& operator -- (int)
    +BigInt& operator -= (const BigInt& other)
    +BigInt operator * (BigInt b)
    +BigInt& operator *= (const BigInt& other)
    +BigInt operator / (BigInt bSigned)
    +BigInt& operator /= (const BigInt& other)
    +BigInt operator % (BigInt b)
    +BigInt& operator %= (const BigInt& other)
  }

  KeyPair o-- PrivateKey
  KeyPair o-- PublicKey

  Encoder <|-- Encryption
  Decoder <|-- Encryption

  Encryption <|.. AsymmetricEncryption
  Encryption <|.. Caesar
  Encryption <|.. ShannonFano
  Encryption o-- Encryptor
  Encryption <-- Message

  AsymmetricEncryption *-- KeysGenerator
  AsymmetricEncryption <-- BigInt
  ' AsymmetricEncryption *-- Encoder
  ' AsymmetricEncryption *-- Decoder

  KeysGenerator *-- KeyPair
  KeysGenerator <-- BigInt
  ' Encoder <-- BigInt
  ' Decoder <-- BigInt
  
@enduml